### ISSUE TITLE
agent的插件使用疑问

### ISSUE THREAD

**Issue by wkshare** [open-falcon/agent#10]
同步plugin后，是否需要重启agent，才会执行同目录下，新增的插件？

同步plugin成功，目录下已经产生脚本。
Portal中配置了对应的插件目录。
再次更新git库，同步plugin成功后，新增了一些脚本，但是这些脚本并没有被agent调用。
知道重启agent后，才被调用。

@UlricQin

**Comment by UlricQin** [comment]
能否稳定复现？

**Comment by wkshare** [comment]
@UlricQin 我最近添加了几个自定义插件，问题依然有。每次plugin/update后，需要再重启一次falcon-agent，才会正常上报数据。

**Comment by UlricQin** [comment]
插件是通过hbs同步下来的，需要几分钟的同步时间，你等了多久？

**Comment by wkshare** [comment]
@UlricQin 使用curl http://<ip>:<port>/plugin/update 后，2秒左右返回success。
同步是成功的，对应agent下plugin目录，文件也已经存在。
但debug日志中，就是没有调用新插件脚本的信息。
直到重启agent，才正常。

hbs会自动同步plugin吗？我没有这么使用，而是手工来同步。这两种同步方式有什么区别吗？

**Comment by UlricQin** [comment]
插件脚本放到git上，然后调用agent的http接口触发一次git pull，插件脚本就到了各个机器。但是这些脚本不会立马执行，哪些机器执行哪些插件是在portal上配置的。agent每隔一段时间去hbs询问，我应该执行哪些插件，hbs就去查数据库，看这个机器应该执行哪些目录下的插件。hbs读取数据库是有缓存的，agent与hbs的通信也是周期性的，所以，调用agent的http接口触发git pull之后，如果portal端的配置没问题，怎么也得个五六分钟，agent才能去第一次执行脚本。

**Comment by wkshare** [comment]
等待时间不是5、6分钟，是一直不调用自定义插件脚本。
不重启agent，就没有数据上报。

T_T @UlricQin

**Comment by UlricQin** [comment]
如果真是的这样的话那就是agent的bug了，需要找时间看看，你也可以看看，如果看到问题提个patch吧

**Comment by UlricQin** [comment]
这个bug解决了，更新common、hbs、agent三个模块的代码，重新编译替换线上程序即可解决

**Comment by wkshare** [comment]
@UlricQin 欢呼:-)
