### ISSUE TITLE
关于磁盘IO收集的问题

### ISSUE THREAD

**Issue by ZeaLoVe** [open-falcon/agent#17]
用命令收集的IO数据是时刻的数据，并不是一段时间的，这样的采集方式可能会有很大的偏差，比如一段时间IO很高，但采集点的时候可能都是0，导致监控上的IO很低。请问，这样的IO数据还算可用数据么？有没对这个采集进行改造的计划？

**Comment by UlricQin** [comment]
没有改造计划。如果是一段时间，这个时间段定多少呢？不同的公司可能有不同的看法。如果觉得现在的做法不合适，可以二次开发，开源代码就是要给你绝对的二次开发的方便，但是主干上的代码，还是会维持现状。
