### ISSUE TITLE
agent 监听服务进程和api接口

### ISSUE THREAD

**Issue by modeyang** [open-falcon/agent#20]
agent能自动监听服务器的基础信息，如网络、内存、io等等
但是能否像zabbix一样能监听某些个服务进程和ping http api接口的功能？
如果能该怎么配置呢？ 谢谢了

**Comment by laiwei** [comment]
服务进程监控 参考文档里面的 proc_num 相关

http://book.open-falcon.com

**Comment by modeyang** [comment]
谢谢  看到了
