### ISSUE TITLE
进程资源监控未实现

### ISSUE THREAD

**Issue by modeyang** [open-falcon/agent#21]
process.cpu.all：进程和它的子进程使用的sys+user的cpu，单位是jiffies
process.cpu.sys：进程和它的子进程使用的sys cpu，单位是jiffies
process.cpu.user：进程和它的子进程使用的user cpu，单位是jiffies
process.swap：进程和它的子进程使用的swap，单位是page
process.fd：进程使用的文件描述符个数
process.mem：进程占用内存，单位byte 
在book.open-falcon里描述的这些关于进程资源的监控在源码里找不到，请问有计划吗？

**Comment by oiooj** [comment]
现在还没有加上进程资源的监控，只有监控进程的数量，这个有时间我可以加上

**Comment by modeyang** [comment]
@oiooj  好的 谢谢

**Comment by laiwei** [comment]
https://github.com/open-falcon/plugin/blob/master/common/60_proc_resource_status.py

参考这个插件脚本
