### ISSUE TITLE
agent端口监听

### ISSUE THREAD

**Issue by scozss** [open-falcon/agent#31]
在agent的如下端口监听中，一般是像默认配置一样内外网都监听呢，还是只监听内网IP呢？如果监听外网对于agent的push数据操作是不是就暴露给了公网?如果只监听内网，对于跨IDC内网不互通的情况，又该如何实时访问agent的监控页面？
~~~
 "http": {
        "enabled": true,
        "listen": ":1988",
        "backdoor": false
    }
~~~

**Comment by laiwei** [comment]
如果有安全顾虑，建议只监听在 127.0.0.1:1988

**Comment by scozss** [comment]
@laiwei 好的

**Comment by stanwu** [comment]
所以是指？
"http": { 
        "enabled": true, 
        "listen": "127.0.0.1:1988", 
        "backdoor": false 
}
