### ISSUE TITLE
agent性能 如何？

### ISSUE THREAD

**Issue by Liuyanglong** [open-falcon/agent#33]
@laiwei  麻烦问下，agent性能不知 官方能否提供下，假设hbs & transter均稳定正常的情况下，不知agent 能支持多大的 api 请求量级。

**Comment by laiwei** [comment]
没有具体的测试数据

不过我可以列一个场景，Hadoop集群相关的metric每个周期大概在100万左右，就是通过一个agent来中转的。

**Comment by Liuyanglong** [comment]
这个周期是多长？100W是 100w条 item value？
