### ISSUE TITLE
为什么Agent不能在mac 和windows上玩啊

### ISSUE THREAD

**Issue by wangxingge** [open-falcon/agent#44]
什么时候能在windows上玩，还有好多的服务器使用的是windows

期待中？要不写一个windows的 nux吧。

**Comment by UlricQin** [comment]
要兼容各个平台，工作量比较大，技术水平也达不到，只能靠社区了。我们文档中可以看到有人写过采集windows指标的一些脚本或者agent，去book中看看吧

**Comment by GitHamburg** [comment]
falcon-agent for mac
https://github.com/GitHamburg/agent-mac.git
