### ISSUE TITLE
kafka的监控

### ISSUE THREAD

**Issue by wanghaisheng** [open-falcon/agent#47]
有没有已经做了kafka的监控

**Comment by UlricQin** [comment]
没有，agent只处理linux基本监控项。kafka这类开源软件如果要监控可以自己写采集脚本推监控数据给transfer，或者写plugin。

**Comment by willsion** [comment]
目前，我是用jmxtrans-agent把监控结果写到一个文件，然后再用py插件读取后，push上来。

**Comment by laiwei** [comment]
@willsion  jmxtrans-agent 这是个什么东西哈

**Comment by chrislee87** [comment]
怎么修改kafka-server-start.sh文件来启动jmxtrans-agent?

**Comment by mzw-g** [comment]
jmxtrans 是个通过jmx协议自定义采集jmx监控项的进程，将采集的监控项转发到监控系统，与open-falcon的插件 jmxmon不同处在于它能自定义采集其他jmx监控项，不仅限于jmx的通用监控项 gc,thread等。
kafka系统的监控项也可以通过jmx协议拉取。jmxtrans地址：https://github.com/jmxtrans/jmxtrans
