### ISSUE TITLE
agent如果配置使用lvs的DR模式的transfer虚IP会出现sock泄露问题

### ISSUE THREAD

**Issue by soarpenguin** [open-falcon/agent#48]
【环境条件】
  1. 部署启动transfer集群使用lvs的DR模式虚IP x.x.x.x；
  2. 在agent中配置transfer为上述虚IP x.x.x.x, 会出现sock泄露问题；
      (注： hbs没问题)

【问题表现】
      falcon-ag 112229 root   18u  sock      0,6      0t0   37104061 can't identify protocol
      falcon-ag 112229 root   19u  sock      0,6      0t0   37104148 can't identify protocol
     falcon-ag 112229 root   20u  sock      0,6      0t0   37104186 can't identify protocol
     falcon-ag 112229 root   21u  sock      0,6      0t0   37104297 can't identify protocol
     falcon-ag 112229 root   22u  sock      0,6      0t0   37104383 can't identify protocol
     falcon-ag 112229 root   23u  sock      0,6      0t0   37104420 can't identify protocol
     falcon-ag 112229 root   24u  sock      0,6      0t0   37104585 can't identify protocol
     falcon-ag 112229 root   25u  sock      0,6      0t0   37104693 can't identify protocol
     falcon-ag 112229 root   26u  sock      0,6      0t0   37104730 can't identify protocol
     falcon-ag 112229 root   27u  sock      0,6      0t0   37104842 can't identify protocol
     falcon-ag 112229 root   28u  sock      0,6      0t0   37104954 can't identify protocol
     falcon-ag 112229 root   29u  sock      0,6      0t0   37104991 can't identify protocol
     falcon-ag 112229 root   30u  sock      0,6      0t0   37105104 can't identify protocol
     falcon-ag 112229 root   31u  sock      0,6      0t0   37105195 can't identify protocol
     falcon-ag 112229 root   32u  sock      0,6      0t0   37105233 can't identify protocol
     falcon-ag 112229 root   33u  sock      0,6      0t0   37105344 can't identify protocol
     falcon-ag 112229 root   34u  sock      0,6      0t0   37105430 can't identify protocol
     falcon-ag 112229 root   35u  sock      0,6      0t0   37105467 can't identify protocol
     falcon-ag 112229 root   36u  IPv6 37105578      0t0        TCP localhost:tr-rsrb-p2->localhost:5048 (CLOSE_WAIT)
     falcon-ag 112229 root   37u  IPv6 37105666      0t0        TCP localhost:tr-rsrb-p2->localhost:ita-manager (CLOSE_WAIT)
     falcon-ag 112229 root   38u  IPv6 37105705      0t0        TCP localhost:tr-rsrb-p2->localhost:intecom-ps1 (CLOSE_WAIT)
     falcon-ag 112229 root   39u  IPv6 37105868      0t0        TCP localhost:tr-rsrb-p2->localhost:ca-1 (CLOSE_WAIT)
     falcon-ag 112229 root   40u  IPv6 37105955      0t0        TCP localhost:tr-rsrb-p2->localhost:authentx (CLOSE_WAIT)
     falcon-ag 112229 root   41u  IPv6 37105992      0t0        TCP localhost:tr-rsrb-p2->localhost:i-net-2000-npr (CLOSE_WAIT)
     falcon-ag 112229 root   42u  IPv6 37106093      0t0        TCP localhost:tr-rsrb-p2->localhost:5075 (CLOSE_WAIT)
     falcon-ag 112229 root   43u  IPv6 37106189      0t0        TCP localhost:tr-rsrb-p2->localhost:5077 (CLOSE_WAIT)
     falcon-ag 112229 root   44u  IPv6 37106229      0t0        TCP localhost:tr-rsrb-p2->localhost:qcp (CLOSE_WAIT)

【预估问题】
和DR不支持长连接有关， agent中的transfer连接是必须保持长连接的；

**Comment by laiwei** [comment]
和DR模式有关系吗？是不是你的lvs配置有问题，我先close了，你有进展再reopen吧
