### ISSUE TITLE
希望agent上传cpu.cnt数据

### ISSUE THREAD

**Issue by xudong-wen** [open-falcon/agent#71]
ganglia web 会根据cpu核数和load来计算服务器状态，根据不同的状态在前端显示为红色，黄色等颜色，非常方便查看问题服务器。查看了falcon agent代码未上传cpu.cnt，所以希望falcon agnet能实现上传cpu.cnt。

**Comment by laiwei** [comment]
是会上传的，cpu.cnt

你确认下

**Comment by xudong-wen** [comment]
确认了下，agent CPU里只返回了以下信息
`return []*model.MetricValue{idle, busy, user, nice, system, iowait, irq, softirq, steal, guest, switches}`
看文档上的cpu.cnt，似乎代码里并未返回。
