### ISSUE TITLE
向agent push数据时，Invalid，但是api接口返回success字串。

### ISSUE THREAD

**Issue by wkshare** [open-falcon/agent#8]
counterType填写错误，填写了一个不支持的名称。

push时，返回success。

这个success，让我调试好久T_T

**Comment by UlricQin** [comment]
错误校验不可能面面俱到的，如果校验的太细致，对Transfer压力比较大（所有的校验我们期望都在中心端来做，这样只需要写一份代码即可），一般错不了的地方，就偷懒不校验了。
