### ISSUE TITLE
自定义PUSH数据疑问

### ISSUE THREAD

**Issue by gangrenroger** [open-falcon/agent#87]
在传统rrdtool中，如果update数据的时间比最后一次update的数据早，update操作将报错，既无法补充提交数据。不知到在agent自定义push数据中是否存在相同的问题，既如果推数据的时间比前一次早，则推送数据报错。因为项目中只要获得一天的数据，数据量在200万左右，如果有此类限制，如果时间乱序push，会出现很多NaN。

**Comment by laiwei** [comment]
必须按照时间戳升序来push数据，不能插入数据

**Comment by gangrenroger** [comment]
如果不是升序，就会只体现在最终数据上，既查询那些有问题的数据Value=None没有上送成功，而没有相关的错误日志？

**Comment by gangrenroger** [comment]
先通过手工排序整理时序的方法来避免自定义PUSH报错。
