### ISSUE TITLE
agent配置transfer、hbs的时候可以填写多个地址

### ISSUE THREAD

**Issue by wkshare** [open-falcon/agent#9]
agent发送数据给多个transfer或者或者hbs的时候，可以配置进行负载均衡，当某个transfer发送故障的时候自动切换。
而不是使用DNS轮询或者haproxy来对transfer、agent进行负载均衡。
如何？

**Comment by UlricQin** [comment]
不太好，因为服务端列表发生了变化，要修改agent的配置。agent要部署在公司所有机器上，升级agent的配置不是个好方法。

我们内部是把transfer和hbs前面架设了lvs，最前面是域名。agent配置的是域名。

**Comment by UlricQin** [comment]
lvs这种负载均衡设备可以保证后端transfer和hbs各个实例负载均衡，让agent直接去请求transfer和hbs列表，后端各个实例负载容易不均衡

**Comment by wkshare** [comment]
@UlricQin 只是让用户多了一种选择，用户可以自行选择是否需要填写多个Transfer。
这样做，并不会影响再使用lvs这样的东西。个人并不是很喜欢lvs，虽然心跳线发生问题的概率非常小，但心跳线依然算是个单点。

比如可以有两个Transfer，一主、一备。我们不做负载均衡
transfer addr1: 这个可以是一个haproxyA，负载到多个transfer(t1,t2,t3...)
transfer addr2: 这个也是一个haporxyB，也负载到同样的多个transfer(t1,t2,t3...)

haproxyA和haproxyB，同一时间只使用一个。

**Comment by UlricQin** [comment]
transfer是无状态的，agent在发数据给transfer的时候，如果出了问题，会持续重试，你如果有多个地址，就简单的把这几个地址做个域名配置到agent中即可。
